'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {withGame,assertClean}=require('./lib/browser');
const out=path.join(__dirname,'out/gauntlet/three-package');fs.mkdirSync(out,{recursive:true});
(async()=>{const report={checks:[]};const log=await withGame('math-ninja',async({page,context})=>{
 const read=()=>page.evaluate(()=>{const g=window.__NinjaToan.G;return {state:g.state,correct:g.correct,wrong:g.wrong,timeLeft:g.timeLeft,readLeft:g.readLeft,hintText:document.querySelector('#hud-hint').textContent,hintHidden:document.querySelector('#hud-hint').hidden,toastHidden:document.querySelector('#toast').hidden,toastShowing:document.querySelector('#toast').classList.contains('show')}});
 const cdp=await context.newCDPSession(page);
 async function swipe(wrong){const before=await read(),key=wrong?'wrong':'correct',deadline=Date.now()+14000;while(Date.now()<deadline){const f=await page.evaluate(wrong=>{const g=window.__NinjaToan.G;if(g.readLeft>0)return null;const f=g.fruits.find(f=>f.kind==='fruit'&&f.launched&&!f.dead&&f.popping<=0&&(wrong?f.value!==g.question.answer:f.value===g.question.answer)&&f.y>g.hudBottom+f.r&&f.y<g.H-f.r);return f&&{x:f.x,y:f.y}},wrong);if(f){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:f.x,y:f.y-55}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:f.x,y:f.y+40}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(70);if((await read())[key]>before[key])return}await page.waitForTimeout(60)}throw Error('Swipe did not land');}
 async function rotateResume(viewport,name){await page.setViewportSize(viewport);await page.waitForFunction(()=>window.__NinjaToan.G.state==='paused');const started=Date.now();assert((await read()).toastShowing);await page.locator('#btn-resume').click();await page.waitForFunction(()=>window.__NinjaToan.G.state==='playing');const s=await read();assert(s.toastHidden&&!s.toastShowing,'resume removes transient toast synchronously');assert.equal(await page.locator('#toast').isVisible(),false);report[name]={elapsedMs:Date.now()-started,...s};assert(report[name].elapsedMs<1600,'resume while old rotation toast would still be present');await page.waitForTimeout(450);await page.screenshot({path:path.join(out,`ninja-${name}-immediate-resume.png`)});}
 await page.locator('#btn-play').click();await page.locator('.level-card').first().click();await page.waitForFunction(()=>window.__NinjaToan.G.state==='playing');await page.waitForTimeout(700);
 await rotateResume({width:844,height:390},'landscape');await swipe(false);report.checks.push('portrait to landscape, immediate resume hides rotation toast, correct touch swipe works');
 await swipe(true);const before=await read();assert(before.readLeft>0&&!before.hintHidden);await rotateResume({width:390,height:844},'reading-portrait');const resumed=await read();assert(resumed.readLeft>0&&!resumed.hintHidden);assert.equal(resumed.hintText,before.hintText);await page.waitForTimeout(250);assert.equal((await read()).timeLeft,resumed.timeLeft);report.checks.push('reading explanation survives rotate/resume and retains timer protection');
 },{viewport:{width:390,height:844},contextOptions:{isMobile:true,hasTouch:true}});assertClean(log,'ninja rotation closure');report.log=log;fs.writeFileSync(path.join(out,'ninja-rotation-closure.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));})().catch(e=>{console.error(e);process.exitCode=1});
