'use strict';
/* Actual pointer/key/DOM input only. Debug state is read to locate rendered targets and
   assert outcomes. Seed controls RNG, never scores/wins. Timed rounds run in real time. */
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),http=require('http');
let pw;try{pw=require('playwright')}catch{pw=require('C:/Users/son.nguyen/AppData/Roaming/Python/Python312/site-packages/playwright/driver/package')}
const root=path.resolve(__dirname,'../..'),out=path.join(__dirname,'out/gauntlet/three-package');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]);if(p.endsWith('/'))p+='index.html';const f=path.join(root,p);if(!f.startsWith(root+path.sep)){res.writeHead(403);res.end();return}fs.readFile(f,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml'})[path.extname(f)]||'application/octet-stream'});res.end(e?'404':b)})});
const views={phone:[390,844],desktop:[1180,820],tablet:[820,1180],landscape:[844,390]};
const selectedGame=process.argv[2],selectedView=process.argv[3];
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await pw.chromium.launch();const results=[];
try{for(const game of selectedGame?[selectedGame]:['math-ninja','cuu-chuong','thap-dong-ho'])for(const name of selectedView?[selectedView]:Object.keys(views)){
 const [width,height]=views[name],context=await browser.newContext({viewport:{width,height},deviceScaleFactor:1,hasTouch:true,isMobile:width<900});
 await context.addInitScript(()=>{let seed=360906;Math.random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296}});
 const page=await context.newPage();page.setDefaultTimeout(12000);const cdp=await context.newCDPSession(page),record={game,view:name,fixture:{width,height,dpr:1,seed:360906},checks:[],errors:[]};results.push(record);
 page.on('pageerror',e=>record.errors.push(String(e)));const shot=async s=>{const file=`${game}-${name}-${s}.png`;await page.screenshot({path:path.join(out,file)});(record.images||(record.images=[])).push(file)};
 const read=()=>page.evaluate(()=>{const x=window.__NinjaToan||window.__CuuChuong||window.__ThapDongHo,g=x.G;return {state:g.state,score:g.score,wrong:g.wrong,correct:g.correct,hearts:g.hearts,shields:g.shields,readLeft:g.readLeft,timeLeft:g.timeLeft,piece:g.piece&&{id:g.piece.id,col:g.piece.col,target:g.piece.target,mode:g.piece.mode,selected:g.piece.selected},board:g.board,targetId:g.targetId,typed:g.typed}});
 const tap=async sel=>{let b=await page.locator(sel).boundingBox();assert(b,sel);if(b.y<0||b.y+b.height>height){await page.locator(sel).evaluate(e=>e.scrollIntoView({block:'center'}));await page.waitForTimeout(150);b=await page.locator(sel).boundingBox()}await page.touchscreen.tap(b.x+b.width/2,b.y+b.height/2)};
 const touch=async(type,x,y)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:/End|Cancel/.test(type)?[]:[{x,y}]});
 const waitRead=()=>page.waitForFunction(()=>!((window.__NinjaToan||window.__CuuChuong).G.readLeft>0),null,{timeout:13000});
 const fruit=async wrong=>{const until=Date.now()+16000;while(Date.now()<until){const f=await page.evaluate(wrong=>{const g=window.__NinjaToan.G;if(g.readLeft>0)return null;const f=g.fruits.find(f=>f.kind==='fruit'&&f.launched&&!f.dead&&f.popping<=0&&(wrong?f.value!==g.question?.answer:f.value===g.question?.answer)&&f.y>g.hudBottom+f.r&&f.y<g.H-f.r);return f&&{x:f.x,y:f.y,r:f.r}},wrong);if(f)return f;await page.waitForTimeout(60)}throw Error('No visible fruit')};
 const swipe=async wrong=>{const f=await fruit(wrong);await touch('touchStart',f.x,f.y-65);await touch('touchMove',f.x,f.y+45);await touch('touchEnd');};
 const answerMeteor=async wrong=>{await page.waitForFunction(()=>window.__CuuChuong.G.meteors.some(m=>m.id===window.__CuuChuong.G.targetId&&!m.dead&&m.popping<=0));const a=await page.evaluate(wrong=>{const g=window.__CuuChuong.G,m=g.meteors.find(m=>m.id===g.targetId);return wrong?101:m.q.answer},wrong);for(const d of String(a))await tap(`[data-key="${d}"]`);await tap('[data-key="fire"]');};
 const drop=async wrong=>{await page.waitForFunction(()=>window.__ThapDongHo.G.piece?.mode==='fall');const s=await read(),col=wrong?(s.piece.target+1)%4:s.piece.target,b=s.board,x=b.x+(col+.5)*b.cell,y=b.y+b.cell*3;await page.touchscreen.tap(x,y);if((await read()).piece?.mode==='fall')await page.touchscreen.tap(x,y);};
 try{
 await page.goto(`http://127.0.0.1:${server.address().port}/${game}/`,{waitUntil:'domcontentloaded'});await page.waitForTimeout(650);await shot('menu');if(game!=='thap-dong-ho')await tap('[data-sec="60"]');await tap('#btn-play');await tap('.level-card:first-child');if(game==='thap-dong-ho'){await shot('lesson');await tap('#btn-lesson-start')}await page.waitForFunction(()=>{const x=window.__NinjaToan||window.__CuuChuong||window.__ThapDongHo;return x.G.state==='playing'});await page.waitForTimeout(800);await shot('gameplay');
 if(game==='math-ninja'){
  for(let attempt=0;attempt<6&&(await read()).wrong===0;attempt++){const f=await fruit(true);await touch('touchStart',f.x,f.y-65);await touch('touchMove',f.x,f.y+45);await page.waitForTimeout(60);if(!(await read()).wrong)await touch('touchEnd');}const before=await read();assert.equal(before.wrong,1);assert(before.readLeft>0);const timer=before.timeLeft;
  for(let i=0;i<10;i++){await page.waitForTimeout(80);await touch('touchMove',i%2?width-30:30,height*.55)}const after=await read();assert.equal(after.wrong,1);assert.equal(after.hearts,2);assert.equal(after.timeLeft,timer);await shot('feedback');
  await waitRead();const second=await fruit(true);await touch('touchMove',second.x,second.y);assert.equal((await read()).wrong,1,'same gesture after reading still cannot double-penalize');await touch('touchCancel');assert.equal(await page.evaluate(()=>[...window.__NinjaToan.G.blades.values()].filter(b=>b.active).length),0);
  for(let attempt=0;attempt<6&&(await read()).correct===0;attempt++){await swipe(false);await page.waitForTimeout(250)}assert((await read()).correct>=1);record.checks.push('same gesture single penalty, timer freeze, cancel, correct swipe');
 }else if(game==='cuu-chuong'){
  await answerMeteor(true);const before=await read();assert.equal(before.wrong,1);assert(before.readLeft>0);const y=await page.evaluate(()=>window.__CuuChuong.G.meteors.map(m=>[m.id,m.y]));await tap('[data-key="1"]');await page.waitForTimeout(900);assert.equal((await read()).timeLeft,before.timeLeft);assert.deepEqual(await page.evaluate(()=>window.__CuuChuong.G.meteors.map(m=>[m.id,m.y])),y);assert.equal((await read()).targetId,before.targetId);await tap('[data-key="del"]');await shot('feedback');await tap('#btn-hint');const hinted=await read();await page.waitForTimeout(600);assert.equal((await read()).timeLeft,hinted.timeLeft);assert.equal((await read()).targetId,hinted.targetId);await answerMeteor(false);assert((await read()).correct>=1);assert.equal((await read()).readLeft,0);record.checks.push('wrong+hint freeze all meteors+timer, edit target stable, correct clears reading');
 }else{
  await page.waitForFunction(()=>window.__ThapDongHo.G.piece?.mode==='fall');let s=await read(),b=s.board,x=b.x+(s.piece.col+.5)*b.cell,y=b.y+b.cell*3;
  await touch('touchStart',x,y);assert.equal((await read()).piece.mode,'fall');await touch('touchMove',b.x+((s.piece.col+1)%4+.5)*b.cell,y);assert.equal((await read()).piece.mode,'fall');await touch('touchCancel');assert.equal((await read()).wrong,0);assert.equal((await read()).piece.selected,false);
  s=await read();x=b.x+(s.piece.col+.5)*b.cell;await page.touchscreen.tap(x,y);assert((await read()).piece.selected);await touch('touchStart',x,y);await touch('touchMove',Math.max(0,b.x-30),y);await touch('touchEnd');assert.equal((await read()).piece.mode,'fall');assert.equal((await read()).piece.selected,false);assert.equal((await read()).wrong,0);
  await drop(true);await page.waitForTimeout(750);assert.equal((await read()).wrong,1);await shot('feedback');await page.waitForFunction(()=>window.__ThapDongHo.G.piece?.mode==='fall');await drop(false);await page.waitForTimeout(600);assert((await read()).correct>=1);record.checks.push('first down selects, drag/cancel never drops, real wrong/correct');
 }
 // Real key route and pause retain progress. Blur is a lifecycle fixture, never outcome injection.
 await page.keyboard.press('Escape');assert.equal((await read()).state,'paused');const paused=await read();await page.waitForTimeout(250);assert.equal((await read()).score,paused.score);await tap('#btn-resume');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.equal((await read()).state,'paused');await tap('#btn-resume');record.checks.push('keyboard pause/resume and blur lifecycle fixture');
 await page.waitForTimeout(450);assert.equal((await read()).state,'playing');record.geometry=await page.evaluate(()=>({scrollW:document.documentElement.scrollWidth,w:innerWidth,buttons:[...document.querySelectorAll('button')].filter(e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden').map(e=>{const r=e.getBoundingClientRect();return {id:e.id,w:r.width,h:r.height}})}));assert.equal(record.geometry.scrollW,width);for(const b of record.geometry.buttons)assert(b.w>=44&&b.h>=44,JSON.stringify(b));
 await shot('after-input');record.performance=await page.evaluate(()=>new Promise(resolve=>{let prev=performance.now();const deltas=[];const frame=now=>{deltas.push(now-prev);prev=now;if(deltas.length<120)return requestAnimationFrame(frame);const d=deltas.slice(1).sort((a,b)=>a-b),n=performance.getEntriesByType('navigation')[0];resolve({frames:d.length,medianMs:d[59],p95Ms:d[113],over33Ms:d.filter(v=>v>33.4).length,domContentLoadedMs:n.domContentLoadedEventEnd,loadMs:n.loadEventEnd})};requestAnimationFrame(frame)}));
 if(name==='phone'&&!process.env.SMOKE){
  const until=Date.now()+145000;while(Date.now()<until&&(await read()).state==='playing'){
   if(game==='math-ninja'){await waitRead();try{await swipe(false)}catch(e){if((await read()).state==='playing')throw e}await page.waitForTimeout(850)}
   else if(game==='cuu-chuong'){try{await answerMeteor(false)}catch(e){if((await read()).state==='playing')throw e}await page.waitForTimeout(700)}
   else {await drop(false);await page.waitForTimeout(650)}
  }
  assert.notEqual((await read()).state,'playing','full round ended');await page.waitForTimeout(1800);await shot('results');record.result=await read();assert(record.result.correct>=1);
  if(game==='thap-dong-ho'){await tap('#btn-quiz');for(let i=0;i<3;i++){const a=await page.evaluate(()=>{const q=window.__ThapDongHo.G.quiz;return q.qs[q.i].choices[0]});await tap(`.choice[data-text=${JSON.stringify(a)}]`);await tap('#btn-quiz-next')}await shot('quiz-complete');record.quiz=await page.evaluate(()=>window.__ThapDongHo.G.quiz);assert(record.quiz.done);await tap('#btn-quiz-replay');}
  else{if(await page.locator('#btn-save-name').isVisible()){await page.locator('#name-input').fill('Gauntlet');await tap('#btn-save-name')}await tap('#btn-again')}
  record.checks.push('legitimate full round/level, result, quiz if applicable, retry');
  await page.reload({waitUntil:'domcontentloaded'});await page.waitForTimeout(450);record.saved=await page.evaluate(()=>{const x=window.__NinjaToan||window.__CuuChuong||window.__ThapDongHo;return x.Store.p()});assert(record.saved.stats&&record.saved.stats.plays>=1,'saved game survives reload');record.checks.push('saved stats survive reload');
 }
 assert.deepEqual(record.errors,[]);record.pass=true;
 }catch(e){record.failure=String(e.stack||e);await shot('failure');process.exitCode=1}finally{console.log(JSON.stringify(record));fs.writeFileSync(path.join(out,`${game}-${name}.json`),JSON.stringify(record,null,2));fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));await context.close()}
 }
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
