'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {withGame,assertClean}=require('./lib/browser');
const out=path.join(__dirname,'out/gauntlet/tank-reading');fs.mkdirSync(out,{recursive:true});
(async()=>{for(const viewport of [{width:844,height:390},{width:780,height:360}])for(const variant of [0,2]){
 const tag=`${viewport.width}x${viewport.height}-elapsed-${variant}`;
 const log=await withGame('xe-tang-thoi-gian',async({page})=>{
 // Content fixture only: a late elapsed-time question, generated by the real question generator.
 // No score/time/game-state writes. Menu/lesson/hint/ack are real DOM input.
 await page.evaluate(variant=>{window.Levels.LEVELS[7].gen=()=>window.Clock.elapsedQ({variant,start:{h:10,m:45},dur:90,act:2,n:4});},variant);
 await page.locator('#btn-play').click();await page.getByText('Thời gian trôi qua',{exact:true}).first().click();await page.locator('#btn-lesson-play').click();await page.waitForFunction(()=>window.__XeTang.G.phase==='ask'&&window.__XeTang.G.state==='playing');await page.locator('#btn-hint').click();await page.waitForTimeout(800);
 const geometry=await page.evaluate(()=>{const box=id=>document.getElementById(id).getBoundingClientRect().toJSON();return {dialog:box('clock-zoom'),question:box('clock-zoom-question'),teaching:box('clock-zoom-teaching'),button:box('btn-clock-close'),faces:Array.from(document.querySelectorAll('#clock-zoom-visual canvas')).map(e=>e.getBoundingClientRect().toJSON()),text:document.getElementById('clock-zoom-teaching').textContent,time:window.__XeTang.G.time};});
 await page.screenshot({path:path.join(out,`${tag}.png`)});fs.writeFileSync(path.join(out,`${tag}.json`),JSON.stringify(geometry,null,2));
 assert.ok(geometry.faces.length>0);for(const b of geometry.faces)assert.ok(b.width>=160&&b.height>=160);
 assert.ok(geometry.button.height>=44&&geometry.button.y>=0&&geometry.button.bottom<=viewport.height);
 assert.ok(geometry.teaching.bottom<=geometry.button.top+1,'ack must not overlay long explanation');
 await page.screenshot({path:path.join(out,`${tag}.png`)});await page.waitForTimeout(1600);assert.equal(await page.evaluate(()=>window.__XeTang.G.time),geometry.time);
 // Synthetic blur is explicitly a handler probe, not evidence of an OS-backgrounded tab.
 await page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.equal(await page.evaluate(()=>window.__XeTang.G.readingHold&&window.__XeTang.G.readingPause),true);await page.locator('#btn-clock-close').click();assert.equal(await page.evaluate(()=>window.__XeTang.G.state),'paused');
 fs.writeFileSync(path.join(out,`${tag}.json`),JSON.stringify({...geometry,fixture:'real elapsedQ generator variant '+variant,blur:'synthetic handler event'},null,2));
 },{viewport,initScript:"localStorage.setItem('xe-tang-thoi-gian-v1',JSON.stringify({players:{p1:{unlockAll:true}}}));"});assertClean(log,tag);console.log('LAYOUT OK',tag);
}})().catch(e=>{console.error(e);process.exitCode=1;});
