"""Regenerate self-contained shared game chrome. Run from any directory.

Only run after game builders hand back index.html/sw.js ownership. Idempotent;
bumps a game's cache once only if generated content or markup changes.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
GAMES = ('math-ninja', 'cuu-chuong', 'me-cung-dong-ho', 'thap-dong-ho',
         'xe-tang-thoi-gian', 'cuoi-ho')
CSS = '''/* Generated by scripts/refresh-games.py; edit the Python source. */
.screen-head .btn { min-width: 44px; min-height: 44px; }
.screen.hidden * { pointer-events: none !important; }
.game-home {
  display: inline-flex; align-items: center; justify-content: center;
  min-height: 44px; padding: 8px 16px; margin: 4px;
  box-sizing: border-box; border: 2px solid #cbd5e1; border-radius: 16px;
  background: #fff; color: #164e63; font: inherit; font-weight: 800;
  text-decoration: none; line-height: 1.3; touch-action: manipulation;
}
.game-home:hover { background: #e6f7fa; border-color: #164e63; }
.game-home:focus-visible { outline: 4px solid #087c9d; outline-offset: 3px; }
.game-home:active { background: #c6edf0; }
.footer-note .game-home { font-size: 14px; }
@media (prefers-reduced-motion: reduce) {
  .game-home { transition: none; animation: none; }
}
'''


def write_changed(path, content):
    if path.exists() and path.read_text(encoding='utf-8') == content:
        return False
    path.write_text(content, encoding='utf-8', newline='\n')
    return True


def refresh(game):
    folder = ROOT / game
    changed = write_changed(folder / 'game-shell.css', CSS)
    path = folder / 'index.html'
    html = path.read_text(encoding='utf-8')
    if 'href="game-shell.css"' not in html:
        html = html.replace('<link rel="stylesheet" href="style.css">',
                            '<link rel="stylesheet" href="style.css">\n  <link rel="stylesheet" href="game-shell.css">')
    html = re.sub(r'<a href="https://3hoa.com"[^>]*>3hoa.com</a>',
                  '<a class="game-home" href="../">← Trang chủ 3hoa</a>', html)
    # Existing quit buttons go to the game's menu; label that destination accurately.
    html = re.sub(r'(id="btn-quit">)[^<]+', r'\1☰ Menu trò chơi', html)
    if 'id="pause-home"' not in html:
        html = re.sub(r'(<button[^>]+id="btn-quit">.*?</button>)',
                      r'\1\n        <a class="game-home" id="pause-home" href="../">← Trang chủ 3hoa</a>', html, count=1)
    changed = write_changed(path, html) or changed
    path = folder / 'sw.js'
    sw = path.read_text(encoding='utf-8')
    if "'./game-shell.css'" not in sw:
        sw = sw.replace("'./style.css',", "'./style.css',\n  './game-shell.css',")
        changed = True
    if changed:
        sw = re.sub(r"(const CACHE = '[a-z-]+-v)(\d+)(')",
                    lambda m: m[1] + str(int(m[2]) + 1) + m[3], sw)
    write_changed(path, sw)
    print(game + (': regenerated + cache bumped' if changed else ': unchanged'))


if __name__ == '__main__':
    import sys
    selected = sys.argv[1:] or GAMES
    if any(g not in GAMES for g in selected):
        raise SystemExit('Unknown game')
    for game in selected:
        refresh(game)
